/**
 * Natural-product family of each `autoLabelDatabase` entry, keyed by its `label`.
 *
 * The family is the template's folder in `data/autoLabel/templates/` and is not
 * stored in the database itself, so it has to be hard-coded here.
 */
export const ENTRY_FAMILIES: Record<string, string> = {
  '2H-Chromene': 'Polyketides',
  Androstane: 'Steroids',
  Anthocyanidine: 'Flavonoids',
  Anthracene: 'Polyketides',
  Anthraquinone: 'Polyketides',
  Anthrone: 'Polyketides',
  'Arylnaphthalene lactone': 'Phenylpropanoids',
  Arylnaphthalene: 'Phenylpropanoids',
  Bisanthrone: 'Polyketides',
  Butyrolactone: 'Phenylpropanoids',
  Campestane: 'Steroids',
  Chalcone: 'Flavonoids',
  Cholane: 'Steroids',
  Cholestane: 'Steroids',
  Coumarin: 'Phenylpropanoids',
  Cucurbitane: 'Tetracyclic triterpenoids',
  Cycloartane: 'Tetracyclic triterpenoids',
  Dammarane: 'Tetracyclic triterpenoids',
  Dibenzocycloctane: 'Phenylpropanoids',
  Dibenzylbutane: 'Phenylpropanoids',
  Dihydroflavonol: 'Flavonoids',
  Ergostane: 'Steroids',
  Estrane: 'Steroids',
  'Flavan-3,4-diol': 'Flavonoids',
  'Flavan-3-ol': 'Flavonoids',
  Flavanone: 'Flavonoids',
  Flavone: 'Flavonoids',
  Flavonol: 'Flavonoids',
  Friedelane: 'Pentacyclic triterpenoids',
  'Furanofuran lignan': 'Phenylpropanoids',
  Furostane: 'Sapogenin',
  Gonane: 'Steroids',
  Isoflavanone: 'Flavonoids',
  Isoflavone: 'Flavonoids',
  Lanostane: 'Tetracyclic triterpenoids',
  Lupane: 'Pentacyclic triterpenoids',
  Lycopene: 'Tetraterpenes',
  'Monofuranic lignan 7-O-7′': 'Phenylpropanoids',
  'Monofuranic lignan 7-O-9′': 'Phenylpropanoids',
  'Monofuranic lignan 9-O-9′': 'Phenylpropanoids',
  Naphtoquinone: 'Polyketides',
  Oleanane: 'Pentacyclic triterpenoids',
  Poriferastane: 'Steroids',
  Pregnane: 'Steroids',
  Protostane: 'Tetracyclic triterpenoids',
  Spirostane: 'Sapogenin',
  Stigmastane: 'Steroids',
  Stilbene: 'Other',
  Taraxastane: 'Pentacyclic triterpenoids',
  Ursane: 'Pentacyclic triterpenoids',
  Xanthone: 'Polyketides',
  'beta-carotene': 'Tetraterpenes',
  cholesterol: 'Core',
  deoxyadenosine: 'Core',
  deoxycytidine: 'Core',
  deoxyguanosine: 'Core',
  deoxythymidine: 'Core',
  deoxyuridine: 'Core',
  'furanose core': 'Core',
  furanose: 'Core',
  methionine: 'Core',
  'pyranose core': 'Core',
  pyranose: 'Core',
  'steroid core': 'Core',
  steroid: 'Core',
};

/** Family assigned to an entry whose label is missing from {@link ENTRY_FAMILIES}. */
export const FALLBACK_FAMILY = 'Other';
